/*
 * Level 1 · 하나 · First Steps
 * Noun sentences: 이에요/예요, 은/는, 이/가 아니에요, 이/가 있어요/없어요.
 */
KG.addLevel({
  id: 1,
  num: "하나",
  ko: "첫걸음",
  title: "First Steps",
  blurb: "Your first sentences: say who someone is, what something is, what it **isn't**, and what you have.",
  lessons: [
    /* ------------------------------------------------------------------ 1-1 */
    {
      id: "1-1",
      sticker: "예요",
      pattern: "N이에요 / 예요",
      title: "It is ~ · I am ~",
      goal: "Say what something is or who someone is, politely. Almost every Korean course starts right here.",
      cards: [
        {
          type: "scene",
          place: "카페 · a café",
          lines: [
            ["minji", "안녕하세요! 저는 민지{예요}.", "Hello! I'm Minji."],
            ["junho", "안녕하세요! 저는 준호{예요}.", "Hello! I'm Junho."],
            ["minji", "준호 씨는 학생{이에요}?", "Junho, are you a student?"],
            ["junho", "아니요, 저는 요리사{예요}. 민지 씨는요?", "No, I'm a cook. And you, Minji?"],
            ["minji", "저는 학생{이에요}!", "I'm a student!"],
          ],
          note: "See the highlighted endings? Sometimes **이에요**, sometimes **예요**. Both mean *am / is / are*. Let's crack the code!",
        },
        {
          type: "discover",
          examples: [["학생{이에요}", "a student"], ["요리사{예요}", "a cook"], ["선생님{이에요}", "a teacher"], ["의사{예요}", "a doctor"]],
          q: "What decides whether you add **이에요** or **예요**?",
          options: ["How the noun ends: consonant or vowel", "Whether you're talking about yourself", "Whether the person is older than you"],
          answer: 0,
          explain: "학**생** and 선생**님** end in a consonant (ㅇ, ㅁ), so they get **이에요**. 요리**사** and 의**사** end in a vowel, so they get **예요**.",
        },
        {
          type: "learn",
          title: "Your first sentence pattern",
          blocks: [
            { p: "**이에요 / 예요** means *am / is / are*. It sticks straight onto a noun, with no space, to say what something or someone **is**." },
            { formula: "Noun + {이에요 / 예요}" },
            { table: { head: ["Noun ends in", "Add", "Example"], rows: [
              ["a consonant (it has a 받침)", "{이에요}", "학생 → 학생{이에요}"],
              ["a vowel (no 받침)", "{예요}", "의사 → 의사{예요}"],
            ] } },
            { p: "A **받침** (batchim) is the consonant sitting at the bottom of a syllable block. 생 has ㅇ at the bottom, so 학생 ends in a 받침. 사 has nothing down there." },
            { ex: [
              ["저는 학생{이에요}.", "I'm a student."],
              ["커피{예요}.", "It's coffee."],
              ["민지 씨는 한국 사람{이에요}.", "Minji is Korean. (lit. a Korea person)"],
            ] },
            { tip: "One form fits everyone! Korean doesn't change the verb for *I / you / she / they*, and it has no words for *a* or *the*. 의사예요 can mean *I'm a doctor*, *she's a doctor* or *they're doctors*. Context decides." },
          ],
        },
        {
          type: "lab",
          lab: "batchim",
          pair: ["이에요", "예요"],
          intro: "Tap a word. Mandu checks its last block: is there a 받침 at the bottom?",
          words: [["학생", "student"], ["의사", "doctor"], ["커피", "coffee"], ["물", "water"], ["가방", "bag"], ["친구", "friend"], ["책", "book"], ["우유", "milk"], ["사람", "person"], ["고양이", "cat"], ["선생님", "teacher"], ["바나나", "banana"]],
        },
        {
          type: "choice",
          sentence: "커피__.",
          en: "It's coffee.",
          options: ["이에요", "예요"],
          answer: 1,
          explain: "커**피** ends in the vowel ㅣ (no 받침), so it takes **예요**: 커피예요.",
        },
        {
          type: "sort",
          q: "Drop each word into the right basket!",
          buckets: ["이에요", "예요"],
          auto: "batchim",
          join: true,
          items: [["가방", "bag", 0], ["친구", "friend", 1], ["책", "book", 0], ["우유", "milk", 1], ["물", "water", 0], ["고양이", "cat", 1], ["사람", "person", 0], ["바나나", "banana", 1]],
          explain: "Ends in a consonant → **이에요**. Ends in a vowel → **예요**.",
        },
        {
          type: "learn",
          title: "Questions and spelling traps",
          blocks: [
            { p: "To ask a **yes/no** question, keep the exact same words and let your voice go **up** at the end. In writing, just add **?**" },
            { ex: [
              ["학생{이에요}?", "Are you a student?"],
              ["네, 학생{이에요}.", "Yes, I'm a student."],
              ["이거 뭐{예요}?", "What is this?"],
              ["사과{예요}.", "It's an apple."],
            ] },
            { tip: "**이거 뭐예요?** (*What is this?*) is one of the handiest phrases in Korean. Point at anything on a menu or in a shop and ask." },
            { warn: "After a **noun** ending in a vowel, it's **예요**, never ~~에요~~. Write 의사예요, not ~~의사에요~~. They sound almost the same, so even Koreans mix them up!" },
            { reveal: { q: "Deep dive: why does 이에요 shrink to 예요?", a: "예요 is a squashed 이에요. After a vowel, the 이 and 에 melt together: 의사 + 이에요 → **의사예요**. After a consonant the full 이에요 stays, and the 받침 slides into it when you speak: 책이에요 sounds like [채기에요]." } },
            { reveal: { q: "Deep dive: what about 입니다?", a: "In the news, in speeches and at job interviews you'll hear the formal **입니다**: 학생입니다, 의사입니다. It works after any noun, with no 받침 check. 이에요/예요 is the polite everyday version you'll use most." } },
          ],
        },
        {
          type: "build",
          en: "I'm an office worker.",
          tiles: ["저는", "회사원이에요."],
          extra: ["회사원예요."],
          alt: ["회사원이에요."],
          explain: "회사**원** ends in ㄴ, a consonant, so it takes **이에요**.",
        },
        {
          type: "fix",
          sentence: "저는 [학생예요].",
          en: "I'm a student.",
          options: ["학생이에요", "학생에요"],
          answer: 0,
          explain: "학**생** has a 받침 (ㅇ), so it takes **이에요**.",
        },
        {
          type: "choice",
          q: "How do you ask **“Is it water?”**",
          options: ["물이에요?", "물예요?", "물이에요."],
          answer: 0,
          explain: "물 ends in ㄹ, a consonant, so it takes **이에요**. A question is the same sentence with **?** and a rising voice.",
          why: {
            "물예요?": "물 ends in the consonant ㄹ, so it needs the full **이에요**.",
            "물이에요.": "Right form, but that's a statement: *It's water.* A question needs **?**",
          },
        },
        {
          type: "fix",
          sentence: "이거 [뭐에요]?",
          en: "What is this?",
          options: ["뭐예요", "뭐이에요"],
          answer: 0,
          explain: "뭐 ends in a vowel, so it's **뭐예요**. 뭐에요 is a very common misspelling, and now you know better than most!",
        },
        {
          type: "match",
          pairs: [["의사예요.", "I'm a doctor."], ["친구예요.", "He's my friend."], ["가방이에요.", "It's a bag."], ["뭐예요?", "What is it?"]],
        },
      ],
      notes: {
        meaning: "am / is / are, said politely",
        forms: [
          ["after a consonant", "N{이에요}", "학생이에요"],
          ["after a vowel", "N{예요}", "의사예요"],
          ["question", "same + ?", "학생이에요?"],
        ],
        examples: [["저는 학생이에요.", "I'm a student."], ["이거 뭐예요?", "What is this?"], ["커피예요.", "It's coffee."]],
        tips: [
          "One form for I, you, he, she and they. No *a* or *the*.",
          "Yes/no questions use the same words with a rising voice.",
          "After a noun ending in a vowel: **예요**, not ~~에요~~.",
          "Formal version: **입니다**, after any noun.",
        ],
      },
    },

    /* ------------------------------------------------------------------ 1-2 */
    {
      id: "1-2",
      sticker: "은/는",
      pattern: "N은 / 는",
      title: "As for ~ (the topic)",
      goal: "Mark what a sentence is about, and contrast it with something else.",
      cards: [
        {
          type: "scene",
          place: "동물병원 · the vet's waiting room",
          lines: [
            ["minji", "어, 준호 씨! 안녕하세요!", "Oh, Junho! Hi!"],
            ["junho", "민지 씨, 안녕하세요! 그 고양이{는} 민지 씨 고양이예요?", "Hi, Minji! Is that cat yours?"],
            ["minji", "네! 이름{은} 나비예요.", "Yes! Her name is Nabi."],
            ["junho", "와, 귀여워요! 이 강아지{는} 콩이에요.", "Aww, so cute! This puppy is Kong."],
            ["minji", "콩{은} 정말 귀여워요!", "Kong is really cute!"],
          ],
          note: "**은** after 이름 and 콩, but **는** after 고양이 and 강아지. Sound familiar? It's the same 받침 game! (Fun fact: 나비, *butterfly*, is the classic Korean name for a cat.)",
        },
        {
          type: "discover",
          examples: [["이름{은}", "name"], ["고양이{는}", "cat"], ["콩{은}", "Kong (a name)"], ["저{는}", "I, me"]],
          q: "When do you use **은**, and when **는**?",
          options: ["은 after a consonant, 는 after a vowel", "은 for people, 는 for animals and things", "은 is polite, 는 is casual"],
          answer: 0,
          explain: "Same rule as 이에요/예요: 이**름** and **콩** end in a consonant → **은**. 고양**이** and **저** end in a vowel → **는**.",
        },
        {
          type: "learn",
          title: "The topic marker",
          blocks: [
            { p: "**은 / 는** marks the **topic**: what the sentence is about. Think *“As for ~ …”*." },
            { formula: "Noun + {은 / 는}" },
            { table: { head: ["Noun ends in", "Add", "Examples"], rows: [
              ["a consonant", "{은}", "이름{은}, 책{은}, 선생님{은}"],
              ["a vowel", "{는}", "저{는}, 친구{는}, 커피{는}"],
            ] } },
            { ex: [
              ["저{는} 민지예요.", "I'm Minji. (As for me, I'm Minji.)"],
              ["제 이름{은} 준호예요.", "My name is Junho."],
              ["이 사람{은} 제 친구예요.", "This person is my friend."],
            ] },
            { tip: "**저** means *I* (polite and humble). **제** means *my*. So: 저는 민지예요 (*I'm Minji*), 제 이름은 민지예요 (*my name is Minji*)." },
          ],
        },
        {
          type: "lab",
          lab: "batchim",
          pair: ["은", "는"],
          intro: "Tap a word to see whether it takes 은 or 는.",
          words: [["저", "I, me"], ["이름", "name"], ["친구", "friend"], ["책", "book"], ["선생님", "teacher"], ["고양이", "cat"], ["한국", "Korea"], ["커피", "coffee"], ["물", "water"], ["사과", "apple"]],
        },
        {
          type: "choice",
          sentence: "제 이름__ 민지예요.",
          en: "My name is Minji.",
          options: ["은", "는"],
          answer: 0,
          explain: "이**름** ends in ㅁ → **은**.",
        },
        {
          type: "choice",
          sentence: "제 친구__ 의사예요.",
          en: "My friend is a doctor.",
          options: ["은", "는"],
          answer: 1,
          explain: "친**구** ends in a vowel → **는**.",
        },
        {
          type: "learn",
          title: "Two superpowers of 은/는",
          blocks: [
            { p: "**1. Contrast.** 은/는 can mean *“…but as for X”*. Put two topics side by side:" },
            { ex: [["저{는} 학생이에요. 친구{는} 선생님이에요.", "I'm a student. My friend, on the other hand, is a teacher."]] },
            { p: "**2. “What about you?”** Add **요** after 은/는 to bounce a question back:" },
            { ex: [["저는 학생이에요. 준호 씨{는요}?", "I'm a student. What about you, Junho?"], ["커피{는요}?", "And coffee? / What about coffee?"]] },
            { tip: "Koreans rarely say *you*. The word 당신 can sound cold, rude or even romantic! For people around your age, use their name + **씨**: 준호 씨는요? For a teacher, boss or elder, use their title, like 선생님. And never put 씨 after your own name." },
            { warn: "Don't start every sentence with 저는. Once the topic is clear, drop it: 저는 민지예요. 학생이에요. Repeating 저는 sounds robotic." },
            { reveal: { q: "Deep dive: 은/는 or 이/가?", a: "Both can look like the *subject* in English, but they do different jobs. **은/는** sets the topic (known or contrasted info). **이/가** points at new information, or at *exactly who/what*. You'll meet 이/가 in the next two lessons." } },
          ],
        },
        {
          type: "build",
          en: "My friend is a teacher.",
          tiles: ["제", "친구는", "선생님이에요."],
          extra: ["친구은", "선생님예요."],
          alt: ["친구는 선생님이에요."],
          explain: "친구 ends in a vowel → **는**. 선생님 ends in a consonant → **이에요**.",
        },
        {
          type: "choice",
          q: "Minji says **저는 학생이에요.** Now she wants to ask whether Junho is one too. What does she say?",
          options: ["준호 씨는요?", "준호 씨예요?", "당신은요?"],
          answer: 0,
          explain: "**~는요?** means *What about ~?* With someone your age, their name + 씨 is the polite way to say *you*.",
          why: {
            "준호 씨예요?": "That asks *Are you Junho?* She already knows his name!",
            "당신은요?": "Grammatically fine, but 당신 sounds cold or oddly intimate. Use his name + 씨.",
          },
        },
        {
          type: "fix",
          sentence: "제 [이름는] 준호예요.",
          en: "My name is Junho.",
          options: ["이름은", "이름이에요"],
          answer: 0,
          explain: "이**름** ends in ㅁ, so it takes **은**.",
        },
        {
          type: "sort",
          q: "은 or 는? Sort the topics!",
          buckets: ["은", "는"],
          auto: "batchim",
          join: true,
          items: [["책", "book", 0], ["저", "I, me", 1], ["한국", "Korea", 0], ["커피", "coffee", 1], ["선생님", "teacher", 0], ["사과", "apple", 1]],
          explain: "Consonant → **은**. Vowel → **는**.",
        },
        {
          type: "match",
          pairs: [["저는", "as for me, I"], ["제 이름은", "my name"], ["친구는요?", "what about your friend?"], ["이 고양이는", "this cat"]],
        },
      ],
      notes: {
        meaning: "the topic marker: *as for ~*",
        forms: [
          ["after a consonant", "N{은}", "이름은"],
          ["after a vowel", "N{는}", "저는"],
          ["what about…?", "N은요? / N는요?", "준호 씨는요?"],
        ],
        examples: [["저는 민지예요.", "I'm Minji."], ["제 이름은 준호예요.", "My name is Junho."], ["저는 학생이에요. 친구는 선생님이에요.", "I'm a student. My friend is a teacher."]],
        tips: [
          "Use it to introduce yourself and to set the topic.",
          "It also contrasts: *X is…, but Y is…*",
          "Instead of *you*: name + 씨 for peers, a title (선생님) for teachers and elders.",
          "저 = I (humble), 제 = my.",
        ],
      },
    },

    /* ------------------------------------------------------------------ 1-3 */
    {
      id: "1-3",
      sticker: "아니에요",
      pattern: "N이 / 가 아니에요",
      title: "It's not ~",
      goal: "Say what something is **not**, and answer yes/no questions the Korean way.",
      cards: [
        {
          type: "scene",
          place: "교실 · a classroom",
          lines: [
            ["junho", "민지 씨, 이거 커피예요?", "Minji, is this coffee?"],
            ["minji", "아니요, 커피{가 아니에요}. 녹차예요.", "No, it's not coffee. It's green tea."],
            ["junho", "아, 이 가방은 민지 씨 가방이에요?", "Oh, is this bag yours, Minji?"],
            ["minji", "아니요, 제 가방{이 아니에요}.", "No, it's not my bag."],
          ],
          note: "To say *is not*, the noun takes **이** or **가**, and then comes **아니에요**.",
        },
        {
          type: "discover",
          examples: [["커피{가} 아니에요", "not coffee"], ["가방{이} 아니에요", "not a bag"], ["의사{가} 아니에요", "not a doctor"], ["학생{이} 아니에요", "not a student"]],
          q: "Before 아니에요 the noun gets **이** or **가**. Which rule is it?",
          options: ["이 after a consonant, 가 after a vowel", "가 after a consonant, 이 after a vowel", "It's random, just memorize it"],
          answer: 0,
          explain: "The same 받침 check: 가**방**, 학**생** → **이**. 커**피**, 의**사** → **가**. Notice a pattern? After a consonant, the particle usually starts with a vowel sound (이에요, 은, 이), so the 받침 can slide into it.",
        },
        {
          type: "learn",
          title: "How to say “is not”",
          blocks: [
            { formula: "Noun + {이 / 가} + {아니에요}" },
            { table: { head: ["Noun ends in", "Pattern", "Example"], rows: [
              ["a consonant", "N{이} 아니에요", "학생{이} 아니에요"],
              ["a vowel", "N{가} 아니에요", "의사{가} 아니에요"],
            ] } },
            { p: "Unlike 이에요/예요, **아니에요** is a separate word, so it gets a **space** in front. Only 이/가 is glued to the noun." },
            { ex: [
              ["저는 의사{가 아니에요}.", "I'm not a doctor."],
              ["이거 물{이 아니에요}. 소주예요!", "This isn't water. It's soju!"],
              ["민지 씨는 선생님{이 아니에요}. 학생이에요.", "Minji isn't a teacher. She's a student."],
            ] },
            { warn: "It's **아니에요**, never ~~아니예요~~. 예요 only comes right after a noun, and 아니 isn't a noun." },
            { tip: "**아니요** = *No.* (the answer word). **아니에요** = *is not*. Bonus: when someone thanks you or apologizes, **아니에요** means *Not at all! Don't mention it!*" },
          ],
        },
        {
          type: "lab",
          lab: "batchim",
          pair: ["이", "가"],
          template: "{np} 아니에요",
          intro: "Tap a word to build its *is not* sentence.",
          words: [["학생", "student"], ["의사", "doctor"], ["커피", "coffee"], ["물", "water"], ["가방", "bag"], ["친구", "friend"], ["고양이", "cat"], ["책", "book"], ["선생님", "teacher"], ["우유", "milk"]],
        },
        {
          type: "choice",
          sentence: "저는 의사__ 아니에요.",
          en: "I'm not a doctor.",
          options: ["이", "가"],
          answer: 1,
          explain: "의**사** ends in a vowel → **가** 아니에요.",
        },
        {
          type: "choice",
          sentence: "이거 물__ 아니에요.",
          en: "This isn't water.",
          options: ["이", "가"],
          answer: 0,
          explain: "물 ends in ㄹ, a consonant → **이** 아니에요.",
        },
        {
          type: "fix",
          sentence: "저는 회사원이 [아니예요].",
          en: "I'm not an office worker.",
          options: ["아니에요", "아니요"],
          answer: 0,
          explain: "Always **아니에요**. 아니요 on its own just means *No*.",
        },
        {
          type: "build",
          en: "It's not a cat. It's a puppy.",
          tiles: ["고양이가", "아니에요.", "강아지예요."],
          extra: ["아니예요.", "고양이이"],
          explain: "고양**이** ends in a vowel → **가** 아니에요. 강아**지** ends in a vowel → **예요**.",
        },
        {
          type: "learn",
          title: "The yes/no trap",
          blocks: [
            { p: "In English, *yes* and *no* answer the **facts**. In Korean, 네 and 아니요 answer whether the **question was right**." },
            { ex: [
              ["A: 학생이 아니에요?", "A: You're not a student?"],
              ["B: 네, 학생이 아니에요.", "B: Right. (Yes,) I'm not a student."],
              ["B: 아니요, 학생이에요!", "B: No, that's wrong. I am a student!"],
            ] },
            { tip: "Think of **네** as *That's right* and **아니요** as *That's not right*. (Heads-up for later: *Isn't it…?* questions like 맛있지 않아요? are answered 네, 맛있어요.)" },
          ],
        },
        {
          type: "choice",
          q: "Junho asks: **학생이 아니에요?** (*You're not a student?*) You are NOT a student. What do you say?",
          options: ["네, 학생이 아니에요.", "아니요, 학생이 아니에요."],
          answer: 0,
          fixed: true,
          explain: "His guess (*not a student*) is right, so you agree with **네**.",
        },
        {
          type: "choice",
          q: "A friend says **고마워요!** (*Thanks!*). What's a natural, humble reply?",
          options: ["아니에요.", "아니요.", "네, 아니에요."],
          answer: 0,
          explain: "**아니에요** here means *Not at all / Don't mention it*. A bare 아니요 sounds like a flat *No*.",
        },
        {
          type: "match",
          pairs: [["아니요.", "No."], ["네.", "Yes. / That's right."], ["커피가 아니에요.", "It's not coffee."], ["학생이 아니에요.", "I'm not a student."]],
        },
      ],
      notes: {
        meaning: "is not / am not / are not",
        forms: [
          ["after a consonant", "N{이 아니에요}", "학생이 아니에요"],
          ["after a vowel", "N{가 아니에요}", "의사가 아니에요"],
        ],
        examples: [["저는 의사가 아니에요.", "I'm not a doctor."], ["커피가 아니에요. 녹차예요.", "It's not coffee. It's green tea."], ["감사합니다! — 아니에요.", "Thank you! — Not at all."]],
        tips: [
          "Space before 아니에요; 이/가 sticks to the noun.",
          "Spelled **아니에요**, never ~~아니예요~~.",
          "네 = *that's right*, 아니요 = *that's not right*.",
          "아니에요 also means *Not at all!*",
        ],
      },
    },

    /* ------------------------------------------------------------------ 1-4 */
    {
      id: "1-4",
      sticker: "있어요",
      pattern: "N이 / 가 있어요 · 없어요",
      title: "There is · I have",
      goal: "Say what exists, what you have, and what you don't. Perfect for shopping!",
      cards: [
        {
          type: "scene",
          place: "편의점 · a convenience store",
          lines: [
            ["junho", "저기요, 김밥{이 있어요}?", "Excuse me, do you have kimbap?"],
            ["minji", "네, {있어요}! 여기요.", "Yes, we do! Here you go."],
            ["junho", "바나나 우유{가 있어요}?", "Do you have banana milk?"],
            ["minji", "아니요, 바나나 우유는 {없어요}. 딸기 우유{가 있어요}.", "No, we don't have banana milk. We have strawberry milk."],
            ["junho", "괜찮아요. 딸기 우유 주세요!", "That's okay. Strawberry milk, please!"],
          ],
          note: "Minji works part-time at the 편의점! **있어요** means *there is / have*. **없어요** means *there isn't / don't have*.",
        },
        {
          type: "discover",
          intro: "One little sentence, two English meanings. Can you guess?",
          examples: [["고양이{가 있어요}.", ""]],
          q: "What can **고양이가 있어요** mean?",
          options: ["There is a cat.", "I have a cat.", "Both, depending on context"],
          answer: 2,
          explain: "있어요 covers both: *there's a cat (here)* and *I have a cat*. Context tells you which.",
        },
        {
          type: "learn",
          title: "있어요 and 없어요",
          blocks: [
            { formula: "Noun + {이 / 가} + {있어요 / 없어요}" },
            { table: { head: ["", "Meaning", "Example"], rows: [
              ["{있어요}", "there is / I have", "펜{이} 있어요."],
              ["{없어요}", "there isn't / I don't have", "돈{이} 없어요."],
            ] } },
            { p: "**이 / 가** is the **subject marker**. Here it marks the thing that exists, or doesn't. Same 받침 rule as before: consonant → **이**, vowel → **가**." },
            { ex: [
              ["펜{이} 있어요?", "Do you have a pen?"],
              ["시간{이} 없어요.", "I don't have time."],
              ["우유{가} 있어요.", "There's milk."],
            ] },
            { tip: "Shopping cheat code: **[thing]이/가 있어요?** = *Do you have [thing]?* It works in every shop, café and restaurant in Korea." },
          ],
        },
        {
          type: "lab",
          lab: "batchim",
          pair: ["이", "가"],
          template: "{np} 있어요",
          intro: "Tap a word to see whether it takes 이 or 가.",
          words: [["펜", "pen"], ["돈", "money"], ["시간", "time"], ["우유", "milk"], ["김밥", "kimbap"], ["고양이", "cat"], ["물", "water"], ["커피", "coffee"], ["질문", "question"], ["친구", "friend"]],
        },
        {
          type: "choice",
          sentence: "바나나 우유__ 있어요?",
          en: "Do you have banana milk?",
          options: ["이", "가"],
          answer: 1,
          explain: "우**유** ends in a vowel → **가**.",
        },
        {
          type: "choice",
          sentence: "김밥__ 없어요.",
          en: "There's no kimbap.",
          options: ["이", "가"],
          answer: 0,
          explain: "김**밥** ends in ㅂ → **이**.",
        },
        {
          type: "sort",
          q: "이 or 가? Stock the convenience store shelves!",
          buckets: ["이", "가"],
          auto: "batchim",
          join: true,
          items: [["김밥", "kimbap", 0], ["라면", "ramyeon", 0], ["우유", "milk", 1], ["떡볶이", "tteokbokki", 1], ["빵", "bread", 0], ["커피", "coffee", 1], ["물", "water", 0], ["주스", "juice", 1]],
          explain: "Consonant → **이**. Vowel → **가**.",
        },
        {
          type: "learn",
          title: "Pro moves",
          blocks: [
            { p: "**1. 제가, not 저가.** A few little words change shape before 가:" },
            { table: { head: ["Word", "+ 이/가", "Meaning"], rows: [["저", "{제가}", "I (polite)"], ["나", "{내가}", "I (casual)"], ["누구", "{누가}", "who"]] } },
            { p: "**2. Who has it?** Use 은/는 for the owner and 이/가 for the thing:" },
            { ex: [["저{는} 고양이{가} 있어요.", "I have a cat. (As for me, a cat exists.)"], ["민지 씨{는} 시간{이} 없어요.", "Minji doesn't have time."]] },
            { p: "**3. Hidden 있어요 words.** Some everyday words are really *something + 있어요/없어요*:" },
            { table: { head: ["Word", "Literally", "Means"], rows: [
              ["맛{있어요}", "taste exists", "it's delicious"],
              ["맛{없어요}", "no taste", "it tastes bad"],
              ["재미{있어요}", "fun exists", "it's fun"],
              ["재미{없어요}", "no fun", "it's boring"],
            ] } },
            { reveal: { q: "Deep dive: why did Minji say 바나나 우유**는** 없어요?", a: "That's the **contrast** power of 은/는 from lesson 1-2: *banana milk, that we don't have (but strawberry milk we do)*. 이/가 simply states what exists; 은/는 compares it with something else." } },
          ],
        },
        {
          type: "fix",
          sentence: "[저가] 펜이 있어요!",
          en: "I have a pen! (answering “Who has a pen?”)",
          options: ["제가", "저이"],
          answer: 0,
          explain: "저 + 가 always becomes **제가**.",
        },
        {
          type: "choice",
          q: "How do you say **“I have a cat.”**?",
          options: ["저는 고양이가 있어요.", "저는 고양이예요.", "저는 고양이가 없어요."],
          answer: 0,
          explain: "Owner + 은/는, thing + 이/가 + 있어요.",
          why: {
            "저는 고양이예요.": "That means *I am a cat*. Cute, but not what you meant!",
            "저는 고양이가 없어요.": "없어요 means *don't have*: *I don't have a cat*.",
          },
        },
        {
          type: "build",
          en: "I don't have time.",
          tiles: ["시간이", "없어요."],
          extra: ["있어요.", "시간가"],
          explain: "시**간** ends in ㄴ → **이**. *Don't have* is **없어요**.",
        },
        {
          type: "match",
          pairs: [["맛있어요", "It's delicious"], ["맛없어요", "It tastes bad"], ["재미있어요", "It's fun"], ["재미없어요", "It's boring"]],
        },
      ],
      notes: {
        meaning: "there is / have · there isn't / don't have",
        forms: [
          ["after a consonant", "N{이} 있어요 / 없어요", "펜이 있어요"],
          ["after a vowel", "N{가} 있어요 / 없어요", "우유가 없어요"],
          ["owner + thing", "A{은/는} B{이/가} 있어요", "저는 고양이가 있어요"],
        ],
        examples: [["김밥이 있어요?", "Do you have kimbap?"], ["시간이 없어요.", "I don't have time."], ["저는 고양이가 있어요.", "I have a cat."]],
        tips: [
          "Shopping: **___이/가 있어요?** = *Do you have ___?*",
          "저 + 가 → **제가**, 나 + 가 → 내가, 누구 + 가 → 누가.",
          "맛있어요 = delicious, 재미있어요 = fun.",
          "은/는 adds contrast: 바나나 우유는 없어요.",
        ],
      },
    },
  ],

  quiz: {
    count: 10,
    extra: [
      {
        type: "choice",
        q: "Pick the correct sentence: **“I'm not a doctor. I'm an office worker.”**",
        options: ["저는 의사가 아니에요. 회사원이에요.", "저는 의사이 아니에요. 회사원이에요.", "저는 의사가 아니예요. 회사원예요.", "저가 의사가 아니에요. 회사원이에요."],
        answer: 0,
        explain: "의사 → **가 아니에요** (spelled 아니에요). 회사원 → **이에요**. And the topic is **저는**.",
      },
      {
        type: "build",
        en: "My friend has a puppy.",
        tiles: ["제", "친구는", "강아지가", "있어요."],
        extra: ["강아지예요.", "친구은"],
        alt: ["친구는 강아지가 있어요."],
        explain: "Owner + 는, thing + 가 + 있어요.",
      },
      {
        type: "fix",
        sentence: "이 고양이는 [나비에요].",
        en: "This cat is Nabi.",
        options: ["나비예요", "나비가요"],
        answer: 0,
        explain: "나**비** ends in a vowel → **예요**.",
      },
      {
        type: "choice",
        q: "Junho asks **고양이가 없어요?** (*You don't have a cat?*). You really don't have one. Answer:",
        options: ["네, 없어요.", "아니요, 없어요."],
        answer: 0,
        fixed: true,
        explain: "His guess is right, so agree with **네**: *Right, I don't.*",
      },
      {
        type: "sort",
        q: "Topic marker: 은 or 는?",
        buckets: ["은", "는"],
        auto: "batchim",
        join: true,
        items: [["이름", "name", 0], ["저", "I, me", 1], ["가방", "bag", 0], ["우유", "milk", 1], ["선생님", "teacher", 0], ["친구", "friend", 1]],
        explain: "Consonant → **은**. Vowel → **는**.",
      },
    ],
  },
});
