/*
 * Level 3 · 셋 · Time Travel
 * Tenses and wishes: -았/었어요, -(으)ㄹ 거예요, -고 싶어요.
 */
KG.addLevel({
  id: 3,
  num: "셋",
  ko: "시간 여행",
  title: "Time Travel",
  blurb: "Talk about yesterday, tomorrow and your dreams: the past tense, the future, and *I want to*.",
  lessons: [
    /* ------------------------------------------------------------------ 3-1 */
    {
      id: "3-1",
      sticker: "았/었",
      pattern: "V-았어요 / 었어요 / 했어요",
      title: "Past tense",
      goal: "Talk about what you did, and what something was like.",
      cards: [
        {
          type: "scene",
          place: "월요일 아침 · Monday morning",
          lines: [
            ["minji", "준호 씨, 주말에 뭐 {했어요}?", "Junho, what did you do on the weekend?"],
            ["junho", "친구를 {만났어요}. 같이 영화를 {봤어요}.", "I met a friend. We watched a movie together."],
            ["minji", "재미{있었어요}?", "Was it fun?"],
            ["junho", "네, 정말 재미{있었어요}! 민지 씨는요?", "Yes, it was really fun! And you?"],
            ["minji", "저는 집에서 {쉬었어요}. 나비는 하루 종일 {잤어요}.", "I rested at home. Nabi slept all day."],
          ],
          note: "So many **ㅆ** at the bottom of blocks: 했, 났, 봤, 었, 잤. That ㅆ is the past tense!",
        },
        {
          type: "discover",
          examples: [["가요 → {갔어요}", "went"], ["먹어요 → 먹{었어요}", "ate"], ["해요 → {했어요}", "did"], ["봐요 → {봤어요}", "saw"]],
          q: "Compare each present form with its past. What's the trick?",
          options: ["Drop 요 from the present, add ㅆ, then 어요", "Add 었어요 to the dictionary form", "Put 안 in front"],
          answer: 0,
          explain: "가요 → 가 → 갔 → **갔어요**. 먹어요 → 먹어 → 먹었 → **먹었어요**. If you can make the present, you can make the past!",
        },
        {
          type: "learn",
          title: "The ㅆ trick",
          blocks: [
            { formula: "present − 요 + {ㅆ어요}" },
            { table: { head: ["Dictionary", "Present", "Past"], rows: [
              ["가다", "가요", "{갔어요}"],
              ["먹다", "먹어요", "먹{었어요}"],
              ["하다", "해요", "{했어요}"],
              ["보다", "봐요", "{봤어요}"],
              ["마시다", "마셔요", "{마셨어요}"],
            ] } },
            { p: "As a rule: last stem vowel ㅏ/ㅗ → **았어요**, any other vowel → **었어요**, 하다 → **했어요**. It's the same vowel harmony as the present, so all your merging rules carry over." },
            { warn: "After ㅆ the ending is **always 어요**: 갔**어요**, never ~~갔아요~~." },
            { tip: "Adjectives and 있다/없다 work too: **좋았어요** (*it was good*), **맛있었어요** (*it was delicious*), **없었어요** (*there wasn't any*)." },
          ],
        },
        {
          type: "lab",
          lab: "verbs",
          mode: "past",
          intro: "Watch the past tense grow out of the present.",
          verbs: [["가다", "go"], ["먹다", "eat"], ["하다", "do"], ["보다", "see, watch"], ["마시다", "drink"], ["만나다", "meet"], ["오다", "come"], ["자다", "sleep"], ["읽다", "read"], ["쉬다", "rest"], ["배우다", "learn"], ["재미있다", "be fun"]],
        },
        {
          type: "steps",
          q: "Put **가다** (*to go*) in the past tense.",
          start: "가다",
          steps: [
            { q: "First, the polite present.", options: ["가요", "가아요", "거요"], answer: 0, show: "가요" },
            { q: "Drop 요 and add ㅆ under the last block.", options: ["갔", "갓", "갇"], answer: 0, show: "갔", hint: "It's the double ㅆ, not a single ㅅ." },
            { q: "Finish it!", options: ["갔어요", "갔아요", "갔요"], answer: 0, show: "갔어요", hint: "After ㅆ it's always 어요." },
          ],
          explain: "가요 → 가 + ㅆ → 갔 + 어요 → **갔어요**.",
        },
        {
          type: "steps",
          q: "Put **마시다** (*to drink*) in the past tense.",
          start: "마시다",
          steps: [
            { q: "First, the polite present.", options: ["마셔요", "마시요", "마사요"], answer: 0, show: "마셔요", hint: "ㅣ + 어 merge into ㅕ." },
            { q: "Drop 요, add ㅆ.", options: ["마셨", "마싰", "마셧"], answer: 0, show: "마셨" },
            { q: "Finish it!", options: ["마셨어요", "마셨아요", "마셨요"], answer: 0, show: "마셨어요" },
          ],
          explain: "마시다 → 마셔요 → 마셨 → **마셨어요**. The merge you learned in the present carries straight into the past.",
        },
        {
          type: "sort",
          q: "았어요 or 었어요? Check the last vowel of the stem.",
          buckets: ["았어요", "었어요"],
          auto: "vowel",
          items: [["살다", "live", 0], ["먹다", "eat", 1], ["놀다", "play", 0], ["읽다", "read", 1], ["받다", "receive", 0], ["웃다", "laugh", 1], ["앉다", "sit", 0], ["있다", "have", 1]],
          explain: "ㅏ / ㅗ → **았어요**. Every other vowel → **었어요**.",
        },
        {
          type: "fix",
          sentence: "어제 친구를 [만났아요].",
          en: "I met a friend yesterday.",
          options: ["만났어요", "만나았어요"],
          answer: 0,
          explain: "After ㅆ the ending is always **어요**: 만났어요.",
        },
        {
          type: "build",
          en: "I watched a movie yesterday.",
          tiles: ["어제", "영화를", "봤어요."],
          extra: ["봐요.", "봤아요."],
          explain: "보다 → 봐요 → **봤어요**.",
        },
        {
          type: "learn",
          title: "Was, wasn't and “Have you eaten?”",
          blocks: [
            { p: "**Nouns** use 이다 in the past: after a consonant **이었어요**, after a vowel **였어요**." },
            { ex: [
              ["저는 학생{이었어요}.", "I was a student."],
              ["그 사람은 의사{였어요}.", "That person was a doctor."],
              ["제 가방이 {아니었어요}.", "It wasn't my bag."],
            ] },
            { p: "**Negatives** work just like before: **안 갔어요** or **가지 않았어요** (*I didn't go*)." },
            { tip: "Culture bite: **밥 먹었어요?** (*Have you eaten?*) is a classic Korean greeting. It's a warm *how are you?*, not a dinner invitation." },
            { reveal: { q: "Deep dive: past or present perfect?", a: "Korean doesn't split *I did* and *I have done*. 먹었어요 can mean *I ate* or *I've eaten*. Context does the rest." } },
          ],
        },
        {
          type: "choice",
          sentence: "저는 학생__.",
          en: "I was a student.",
          options: ["이었어요", "였어요", "이에요"],
          answer: 0,
          explain: "학**생** ends in a consonant → **이었어요**.",
          why: { "였어요": "였어요 is for nouns ending in a vowel (의사였어요).", "이에요": "That's present: *I am a student.*" },
        },
        {
          type: "choice",
          q: "**“Was it delicious?”**",
          options: ["맛있었어요?", "맛있어요?", "맛있었아요?"],
          answer: 0,
          explain: "맛있다 → 맛있어요 → **맛있었어요?**",
          why: { "맛있어요?": "That's present: *Is it delicious?*", "맛있었아요?": "After ㅆ it's always 어요." },
        },
        {
          type: "choice",
          q: "A Korean coworker asks **밥 먹었어요?** What do they mean?",
          options: ["Have you eaten? (a friendly hello)", "Do you want to eat with me right now?", "Did you cook rice?"],
          answer: 0,
          explain: "It's a caring greeting. Just answer **네, 먹었어요!** or **아직이요** (*not yet*).",
        },
        {
          type: "match",
          q: "Match each present form to its past.",
          pairs: [["가요", "갔어요"], ["와요", "왔어요"], ["해요", "했어요"], ["마셔요", "마셨어요"]],
        },
      ],
      notes: {
        meaning: "the past tense: *did / was / have done*",
        forms: [
          ["last vowel ㅏ or ㅗ", "stem + {았어요}", "갔어요, 봤어요"],
          ["any other vowel", "stem + {었어요}", "먹었어요, 마셨어요"],
          ["하다", "{했어요}", "공부했어요"],
          ["nouns", "N{이었어요} / N{였어요}", "학생이었어요"],
        ],
        examples: [["주말에 뭐 했어요?", "What did you do on the weekend?"], ["영화를 봤어요.", "I watched a movie."], ["재미있었어요!", "It was fun!"]],
        tips: [
          "Shortcut: present − 요 + ㅆ어요.",
          "After ㅆ it's always 어요: 갔어요, never ~~갔아요~~.",
          "밥 먹었어요? = a friendly *how are you?*",
          "Negative: 안 갔어요 / 가지 않았어요.",
        ],
      },
    },

    /* ------------------------------------------------------------------ 3-2 */
    {
      id: "3-2",
      sticker: "ㄹ 거예요",
      pattern: "V-(으)ㄹ 거예요",
      title: "Will · going to",
      goal: "Talk about plans, and make guesses about the future.",
      cards: [
        {
          type: "scene",
          place: "금요일 저녁 · Friday evening",
          lines: [
            ["junho", "민지 씨, 내일 뭐 {할 거예요}?", "Minji, what are you going to do tomorrow?"],
            ["minji", "친구를 {만날 거예요}. 같이 쇼핑{할 거예요}.", "I'm going to meet a friend. We're going shopping together."],
            ["junho", "좋아요! 저는 집에서 책을 {읽을 거예요}. 나비는요?", "Nice! I'm going to read a book at home. And Nabi?"],
            ["minji", "나비는 하루 종일 {잘 거예요}!", "Nabi will sleep all day!"],
          ],
          note: "할, 만날 and 잘 get a **ㄹ** tucked under them, but 읽 gets **을**. Can you guess why?",
        },
        {
          type: "discover",
          examples: [["만나다 → 만{날 거예요}", "will meet"], ["하다 → {할 거예요}", "will do"], ["읽다 → 읽{을 거예요}", "will read"], ["먹다 → 먹{을 거예요}", "will eat"]],
          q: "When do you add **ㄹ**, and when **을**?",
          options: ["Stem ends in a vowel → ㄹ; in a consonant → 을", "Short verbs → ㄹ; long verbs → 을", "ㄹ for plans, 을 for guesses"],
          answer: 0,
          explain: "만나 and 하 end in a vowel, so ㄹ slides under the last block: 만**날**, **할**. 읽 and 먹 already have a 받침, so they take **을**.",
        },
        {
          type: "learn",
          title: "Will / going to",
          blocks: [
            { p: "**-(으)ㄹ 거예요** talks about the **future**: plans, intentions and guesses." },
            { table: { head: ["Stem ends in", "Add", "Examples"], rows: [
              ["a vowel", "{ㄹ 거예요}", "가다 → {갈 거예요}, 보다 → {볼 거예요}"],
              ["a consonant", "{을 거예요}", "먹다 → {먹을 거예요}, 읽다 → {읽을 거예요}"],
              ["ㄹ already", "{거예요}", "살다 → {살 거예요}, 만들다 → {만들 거예요}"],
            ] } },
            { p: "The ㄹ joins the last block as its 받침: 가 + ㄹ → **갈**. If the stem already ends in ㄹ, nothing changes: 살 → **살 거예요**." },
            { ex: [
              ["내일 친구를 {만날 거예요}.", "I'm going to meet a friend tomorrow."],
              ["주말에 집에서 {쉴 거예요}.", "I'll rest at home this weekend."],
              ["저녁에 김밥을 {먹을 거예요}.", "I'm going to eat kimbap this evening."],
            ] },
            { warn: "There's a **space** before 거예요, and it's spelled **거예요**, never ~~거에요~~. Remember lesson 1-1? 거 ends in a vowel → 예요!" },
            { tip: "Say it like a local: 갈 거예요 sounds like [갈 **꺼**예요]. The ㄱ after ㄹ tenses up, but the spelling stays 거." },
          ],
        },
        {
          type: "lab",
          lab: "verbs",
          mode: "future",
          intro: "See where the ㄹ goes for each verb.",
          verbs: [["가다", "go"], ["하다", "do"], ["보다", "see, watch"], ["만나다", "meet"], ["먹다", "eat"], ["읽다", "read"], ["앉다", "sit"], ["살다", "live"], ["만들다", "make"], ["놀다", "play"], ["쉬다", "rest"], ["마시다", "drink"]],
        },
        {
          type: "choice",
          sentence: "내일 영화를 __ 거예요.",
          en: "I'm going to watch a movie tomorrow.",
          options: ["볼", "보을", "봘"],
          answer: 0,
          explain: "보 ends in a vowel, so ㄹ goes under it: **볼** 거예요.",
        },
        {
          type: "choice",
          sentence: "저녁에 김밥을 __ 거예요.",
          en: "I'll eat kimbap this evening.",
          options: ["먹을", "멀", "먹"],
          answer: 0,
          explain: "먹 already has a 받침 → **먹을** 거예요.",
        },
        {
          type: "sort",
          q: "Which future form does each verb take?",
          buckets: ["+ ㄹ 거예요", "+ 을 거예요", "ㄹ stem: + 거예요"],
          items: [
            ["가다", "go", 0, "가 ends in a vowel → add ㄹ: **갈 거예요**"],
            ["먹다", "eat", 1, "먹 has a 받침 → **먹을 거예요**"],
            ["살다", "live", 2, "살 already ends in ㄹ → **살 거예요**"],
            ["마시다", "drink", 0, "마시 ends in a vowel → **마실 거예요**"],
            ["읽다", "read", 1, "읽 has a 받침 → **읽을 거예요**"],
            ["만들다", "make", 2, "만들 already ends in ㄹ → **만들 거예요**"],
            ["하다", "do", 0, "하 ends in a vowel → **할 거예요**"],
            ["앉다", "sit", 1, "앉 has a 받침 → **앉을 거예요**"],
            ["놀다", "play", 2, "놀 already ends in ㄹ → **놀 거예요**"],
          ],
          explain: "Vowel → **ㄹ 거예요**. Consonant → **을 거예요**. Already ㄹ → just **거예요**.",
        },
        {
          type: "steps",
          q: "Make **읽다** (*to read*) future.",
          start: "읽다",
          steps: [
            { q: "Find the stem.", options: ["읽", "읽어", "일"], answer: 0, show: "읽" },
            { q: "읽 ends in a consonant. Add…", options: ["을 거예요", "ㄹ 거예요", "거예요"], answer: 0, show: "읽을 거예요" },
          ],
          explain: "Consonant stem → **을 거예요**: 읽을 거예요.",
        },
        {
          type: "choice",
          q: "**만들다** (*to make*) → future?",
          options: ["만들 거예요", "만들을 거예요", "만드을 거예요"],
          answer: 0,
          explain: "The stem already ends in ㄹ, so just add **거예요**.",
        },
        {
          type: "fix",
          sentence: "내일 친구를 만날 [거에요].",
          en: "I'm going to meet a friend tomorrow.",
          options: ["거예요", "꺼예요"],
          answer: 0,
          explain: "거 ends in a vowel → **예요**. And even though it sounds like [꺼], it's spelled **거**.",
        },
        {
          type: "learn",
          title: "Guessing the future",
          blocks: [
            { p: "With adjectives, or things you can't control, -(으)ㄹ 거예요 becomes a **guess**: *it'll probably…*" },
            { ex: [
              ["재미있{을 거예요}!", "It'll be fun!"],
              ["내일 비가 {올 거예요}.", "It'll probably rain tomorrow."],
              ["민지 씨는 집에 {있을 거예요}.", "Minji is probably at home."],
            ] },
            { tip: "Handy time words: **내일** (*tomorrow*), **주말에** (*on the weekend*), **다음 주에** (*next week*), **나중에** (*later*)." },
            { reveal: { q: "Deep dive: what is 거?", a: "거 is the casual form of **것** (*thing*). So 갈 거예요 is literally *it's a going-to-go thing*. In formal writing you'll see **갈 것입니다**." } },
            { reveal: { q: "Deep dive: the present tense for plans", a: "For fixed plans, Koreans often just use the present: **내일 가요** (*I'm going tomorrow*). -(으)ㄹ 거예요 adds a feeling of intention or prediction." } },
          ],
        },
        {
          type: "build",
          en: "I'm going to study at home tomorrow.",
          tiles: ["내일", "집에서", "공부할", "거예요."],
          extra: ["집에", "공부을"],
          explain: "Studying is an action → 집**에서**. 공부하 → **공부할** 거예요.",
        },
        {
          type: "choice",
          q: "Your friend is nervous about a trip. Cheer them up: **“It'll be fun!”**",
          options: ["재미있을 거예요!", "재미있었어요!", "재미있어요?"],
          answer: 0,
          explain: "-(으)ㄹ 거예요 makes a guess about the future.",
          why: { "재미있었어요!": "That's past: *It was fun!*", "재미있어요?": "That's a present-tense question: *Is it fun?*" },
        },
      ],
      notes: {
        meaning: "will / going to (plans and guesses)",
        forms: [
          ["stem ends in a vowel", "stem + {ㄹ 거예요}", "갈 거예요"],
          ["stem ends in a consonant", "stem + {을 거예요}", "먹을 거예요"],
          ["stem ends in ㄹ", "stem + {거예요}", "살 거예요"],
        ],
        examples: [["내일 뭐 할 거예요?", "What are you going to do tomorrow?"], ["친구를 만날 거예요.", "I'm going to meet a friend."], ["재미있을 거예요!", "It'll be fun!"]],
        tips: [
          "Space before 거예요.",
          "Spelled **거예요**, said [꺼예요].",
          "With adjectives it's a guess: 맛있을 거예요.",
          "Irregulars change: 듣다 → 들을 거예요.",
        ],
      },
    },

    /* ------------------------------------------------------------------ 3-3 */
    {
      id: "3-3",
      sticker: "고 싶어요",
      pattern: "V-고 싶어요",
      title: "I want to ~",
      goal: "Say what you want to do, and talk about what other people want.",
      cards: [
        {
          type: "scene",
          place: "여행 계획 · planning a trip",
          lines: [
            ["minji", "준호 씨, 어디에 가{고 싶어요}?", "Junho, where do you want to go?"],
            ["junho", "부산에 가{고 싶어요}! 바다를 보{고 싶어요}.", "I want to go to Busan! I want to see the sea."],
            ["minji", "저는 제주도에 가{고 싶어요}. 귤을 먹{고 싶어요}!", "I want to go to Jeju Island. I want to eat tangerines!"],
            ["junho", "나비는요?", "And Nabi?"],
            ["minji", "나비는 집에서 자{고 싶어 해요}.", "Nabi wants to sleep at home."],
          ],
          note: "**-고 싶어요** = *I want to*. For someone else, like Nabi, Koreans say **-고 싶어 해요**. (Jeju Island is famous for its tangerines, 귤!)",
        },
        {
          type: "discover",
          examples: [["가다 → 가{고 싶어요}", "want to go"], ["먹다 → 먹{고 싶어요}", "want to eat"], ["보다 → 보{고 싶어요}", "want to see"], ["하다 → 하{고 싶어요}", "want to do"]],
          q: "Does the 받침 or the vowel change anything for **-고 싶어요**?",
          options: ["No, it's the same for every stem", "Yes, 받침 stems take 이고 싶어요", "Yes, ㅏ/ㅗ stems take 아고 싶어요"],
          answer: 0,
          explain: "Just stem + **고 싶어요**. No 받침 check, no vowel harmony. Enjoy the easiest pattern in the diary!",
        },
        {
          type: "learn",
          title: "I want to…",
          blocks: [
            { formula: "Stem + {고 싶어요}" },
            { ex: [
              ["한국에 가{고 싶어요}.", "I want to go to Korea."],
              ["떡볶이를 먹{고 싶어요}.", "I want to eat tteokbokki."],
              ["뭐 하{고 싶어요}?", "What do you want to do?"],
            ] },
            { p: "**싶다** is the part that changes for tense and negation:" },
            { table: { head: ["", "Form", "Meaning"], rows: [
              ["present", "가고 {싶어요}", "I want to go"],
              ["past", "가고 {싶었어요}", "I wanted to go"],
              ["negative", "가고 {싶지 않아요}", "I don't want to go"],
            ] } },
            { warn: "싶어요 needs a **verb** in front of it. To want a thing, add a verb: ~~커피 싶어요~~ → 커피를 **마시고** 싶어요." },
            { tip: "The most famous K-drama line: **보고 싶어요**. Literally *I want to see you*; really *I miss you*." },
          ],
        },
        {
          type: "choice",
          sentence: "저는 비빔밥을 먹__ 싶어요.",
          en: "I want to eat bibimbap.",
          options: ["고", "지", "어"],
          answer: 0,
          explain: "Stem + **고 싶어요**: 먹고 싶어요.",
        },
        {
          type: "choice",
          q: "**“What do you want to do?”**",
          options: ["뭐 하고 싶어요?", "뭐 했어요?", "뭐 할 거예요?"],
          answer: 0,
          explain: "했어요 = *did*, 할 거예요 = *will do*, **하고 싶어요** = *want to do*.",
        },
        {
          type: "build",
          en: "I want to go to Korea.",
          tiles: ["한국에", "가고", "싶어요."],
          extra: ["한국에서", "갈"],
          explain: "Going somewhere → **에**. Then 가 + **고 싶어요**.",
        },
        {
          type: "fix",
          sentence: "저는 영화를 보고 [싶아요].",
          en: "I want to watch a movie.",
          options: ["싶어요", "싶요"],
          answer: 0,
          explain: "싶 has the vowel ㅣ, so it takes **어요**. Your vowel-harmony skills still matter!",
        },
        {
          type: "learn",
          title: "Other people's wishes",
          blocks: [
            { p: "Korean is careful about other people's feelings: you can't really *know* what someone else wants. So for a third person, use **-고 싶어 해요** (*they show that they want to*)." },
            { table: { head: ["Who", "Form", "Example"], rows: [
              ["I (statement)", "-고 {싶어요}", "저는 자고 싶어요."],
              ["you (question)", "-고 {싶어요}?", "뭐 먹고 싶어요?"],
              ["he / she / they", "-고 {싶어 해요}", "나비는 자고 싶어 해요."],
            ] } },
            { reveal: { q: "Deep dive: 을/를 or 이/가?", a: "With -고 싶다 the object can take **이/가** to show a strong craving: **떡볶이가 먹고 싶어요!** (*I'm craving tteokbokki!*). 떡볶이를 먹고 싶어요 is the neutral version. Both are correct." } },
          ],
        },
        {
          type: "choice",
          q: "**“Minji wants to eat tteokbokki.”**",
          options: ["민지 씨는 떡볶이를 먹고 싶어 해요.", "민지 씨는 떡볶이를 먹고 싶어요.", "민지 씨는 떡볶이를 먹을 싶어요."],
          answer: 0,
          explain: "For someone else, use **-고 싶어 해요**.",
          why: {
            "민지 씨는 떡볶이를 먹고 싶어요.": "싶어요 is for *I* (or *you* in a question). For Minji, use 싶어 해요.",
            "민지 씨는 떡볶이를 먹을 싶어요.": "싶다 always comes after **-고**.",
          },
        },
        {
          type: "steps",
          q: "Say **“I wanted to drink coffee.”**",
          start: "마시다",
          say: "커피를 마시고 싶었어요.",
          steps: [
            { q: "Stem + want:", options: ["마시고 싶다", "마셔고 싶다", "마실 싶다"], answer: 0, show: "마시고 싶다" },
            { q: "Now put 싶다 in the past:", options: ["마시고 싶었어요", "마시고 싶았어요", "마셨고 싶어요"], answer: 0, show: "커피를 마시고 싶었어요", hint: "Only 싶다 changes. Its vowel is ㅣ → 었어요." },
          ],
          explain: "싶다 → 싶어요 → **싶었어요** (ㅣ → 었어요). The verb in front of 고 never changes.",
        },
        {
          type: "match",
          pairs: [["보고 싶어요", "I miss you"], ["자고 싶어요", "I want to sleep"], ["가고 싶지 않아요", "I don't want to go"], ["먹고 싶었어요", "I wanted to eat"]],
        },
      ],
      notes: {
        meaning: "want to (do something)",
        forms: [
          ["any verb stem", "stem + {고 싶어요}", "가고 싶어요"],
          ["past", "stem + {고 싶었어요}", "가고 싶었어요"],
          ["someone else", "stem + {고 싶어 해요}", "자고 싶어 해요"],
        ],
        examples: [["한국에 가고 싶어요.", "I want to go to Korea."], ["뭐 먹고 싶어요?", "What do you want to eat?"], ["보고 싶어요.", "I miss you."]],
        tips: [
          "No 받침 or vowel rules at all.",
          "Needs a verb: 커피를 마시고 싶어요.",
          "Someone else: -고 싶어 해요.",
          "Negative: 가고 싶지 않아요.",
        ],
      },
    },
  ],

  quiz: {
    count: 10,
    extra: [
      {
        type: "choice",
        q: "**“I studied yesterday. Tomorrow I'll rest.”**",
        options: ["어제 공부했어요. 내일 쉴 거예요.", "어제 공부할 거예요. 내일 쉬었어요.", "어제 공부했아요. 내일 쉴 거에요."],
        answer: 0,
        explain: "Past for yesterday (**공부했어요**), future for tomorrow (**쉴 거예요**).",
      },
      {
        type: "sort",
        q: "Past or future?",
        buckets: ["past", "future"],
        items: [
          ["먹었어요", "", 0, "See the ㅆ in 었? That's the past."],
          ["갈 거예요", "", 1, "(으)ㄹ 거예요 is the future."],
          ["봤어요", "", 0, "봤 has ㅆ → past."],
          ["읽을 거예요", "", 1, "을 거예요 → future."],
          ["했어요", "", 0, "했 has ㅆ → past."],
          ["살 거예요", "", 1, "ㄹ 거예요 → future."],
        ],
        explain: "ㅆ어요 → past. -(으)ㄹ 거예요 → future.",
      },
      {
        type: "build",
        en: "I wanted to go to Busan.",
        tiles: ["부산에", "가고", "싶었어요."],
        extra: ["싶었아요.", "갔고"],
        explain: "가 + 고 싶다, then 싶다 → **싶었어요**.",
      },
      {
        type: "choice",
        sentence: "어제 친구가 집에 __.",
        en: "My friend came over yesterday.",
        options: ["왔어요", "올 거예요", "와요"],
        answer: 0,
        explain: "어제 (*yesterday*) → past: 오다 → 와요 → **왔어요**.",
      },
      {
        type: "choice",
        q: "**“It wasn't fun.”**",
        options: ["재미없었어요.", "재미없을 거예요.", "재미있었어요."],
        answer: 0,
        explain: "재미없다 → 재미없어요 → **재미없었어요**.",
      },
    ],
  },
});
