/*
 * Level 2 · 둘 · On the Move
 * Verb sentences: -아요/어요, 을/를, 에 vs 에서, 안 / -지 않아요.
 */
KG.addLevel({
  id: 2,
  num: "둘",
  ko: "움직여요",
  title: "On the Move",
  blurb: "Verbs! Say what people **do**: the polite present tense, objects, places, and how to say *don't*.",
  lessons: [
    /* ------------------------------------------------------------------ 2-1 */
    {
      id: "2-1",
      sticker: "아요/어요",
      pattern: "V-아요 / 어요 / 해요",
      title: "Present tense, politely",
      goal: "Turn any regular verb from the dictionary into a polite everyday sentence. This one ending unlocks hundreds of verbs.",
      cards: [
        {
          type: "scene",
          place: "영상 통화 · a video call",
          lines: [
            ["minji", "준호 씨, 지금 뭐 {해요}?", "Junho, what are you doing right now?"],
            ["junho", "요리{해요}! 민지 씨는요?", "Cooking! And you?"],
            ["minji", "저는 공부{해요}. 그리고 나비는 {자요}.", "I'm studying. And Nabi is sleeping."],
            ["junho", "하하, 나비는 맨날 {자요}!", "Haha, Nabi sleeps all the time!"],
          ],
          note: "해요 and 자요 are verbs! In the dictionary they're **하다** (*to do*) and **자다** (*to sleep*). Let's see how 다 turns into 요.",
        },
        {
          type: "learn",
          title: "Meet the verb stem",
          blocks: [
            { p: "Every verb and adjective in the dictionary ends in **다**: 가다 (*to go*), 먹다 (*to eat*), 하다 (*to do*). Chop off 다 and what's left is the **stem**." },
            { table: { head: ["Dictionary form", "Stem", "Polite present"], rows: [["가다", "가", "{가요}"], ["먹다", "먹", "{먹어요}"], ["하다", "하", "{해요}"]] } },
            { p: "To talk politely, add **아요**, **어요** or **해요** to the stem. Which one? It depends on the **last vowel of the stem**." },
            { formula: "Stem + {아요 / 어요 / 해요}" },
          ],
        },
        {
          type: "discover",
          examples: [["살다 → 살{아요}", "live"], ["먹다 → 먹{어요}", "eat"], ["놀다 → 놀{아요}", "play"], ["읽다 → 읽{어요}", "read"], ["좋다 → 좋{아요}", "be good"], ["있다 → 있{어요}", "have, exist"]],
          q: "Look at the vowel in each stem: 살, 놀, 좋 versus 먹, 읽, 있. When does **아요** appear?",
          options: ["When the vowel is ㅏ or ㅗ", "When the stem has a 받침", "When the verb is short"],
          answer: 0,
          explain: "살 (ㅏ), 놀 (ㅗ), 좋 (ㅗ) → **아요**. 먹 (ㅓ), 읽 (ㅣ), 있 (ㅣ) → **어요**. ㅏ and ㅗ are the *bright* vowels, and they like to stick together.",
        },
        {
          type: "learn",
          title: "The three rules",
          blocks: [
            { table: { head: ["Last vowel of the stem", "Add", "Examples"], rows: [
              ["ㅏ or ㅗ", "{아요}", "살다 → 살아요 (*live*) · 좋다 → 좋아요 (*be good*)"],
              ["any other vowel", "{어요}", "먹다 → 먹어요 (*eat*) · 읽다 → 읽어요 (*read*)"],
              ["하다", "{해요}", "하다 → 해요 (*do*) · 공부하다 → 공부해요 (*study*)"],
            ] } },
            { tip: "You already know two! **있어요 / 없어요** are just 있다 / 없다 + 어요." },
            { p: "Adjectives follow exactly the same rules. In Korean they act like verbs, so there's no separate word for *is*: 좋다 → **좋아요** (*it's good*), 작다 → **작아요** (*it's small*)." },
            { reveal: { q: "Deep dive: why bright and dark vowels?", a: "It's called **vowel harmony** (모음조화). ㅏ and ㅗ are *bright* (양성) vowels; the rest are *dark* (음성). Endings that start with 아/어 copy the stem's brightness. You'll see this 아/어 choice again in the past tense and in many later patterns, so it's worth getting comfy with now." } },
          ],
        },
        {
          type: "lab",
          lab: "verbs",
          mode: "present",
          intro: "Pick a verb and watch it steam into its polite form, one step at a time.",
          verbs: [["가다", "go"], ["먹다", "eat"], ["하다", "do"], ["보다", "see, watch"], ["마시다", "drink"], ["배우다", "learn"], ["살다", "live"], ["읽다", "read"], ["오다", "come"], ["공부하다", "study"], ["쉬다", "rest"], ["쓰다", "write"]],
        },
        {
          type: "steps",
          q: "Steam **먹다** (*to eat*) into its polite present form.",
          start: "먹다",
          steps: [
            { q: "First, find the stem.", options: ["먹", "먹다", "머"], answer: 0, show: "먹" },
            { q: "The last vowel is ㅓ. Which ending?", options: ["아요", "어요", "해요"], answer: 1, show: "먹 + 어요", hint: "ㅓ isn't one of the bright vowels (ㅏ, ㅗ)." },
            { q: "먹 has a 받침, so nothing merges. The result?", options: ["먹어요", "머거요", "먹아요"], answer: 0, show: "먹어요", hint: "머거요 is how it *sounds*, but the spelling keeps the stem: 먹 + 어요." },
          ],
          explain: "먹다 → 먹 → ㅓ isn't ㅏ/ㅗ → **먹어요**. It's pronounced [머거요] because the ㄱ slides over, but it's spelled 먹어요.",
        },
        {
          type: "sort",
          q: "아요 or 어요? Check the last vowel of each stem.",
          buckets: ["아요", "어요"],
          auto: "vowel",
          items: [["살다", "live", 0], ["먹다", "eat", 1], ["놀다", "play", 0], ["읽다", "read", 1], ["좋다", "be good", 0], ["있다", "have", 1], ["앉다", "sit", 0], ["웃다", "laugh", 1]],
          explain: "ㅏ or ㅗ → **아요**. Every other vowel → **어요**.",
        },
        {
          type: "learn",
          title: "When vowels bump into each other",
          blocks: [
            { p: "If the stem ends in a **vowel** (no 받침), the 아/어 of the ending merges into it. Same rules, shorter words:" },
            { table: { head: ["Stem ends in", "What happens", "Examples"], rows: [
              ["ㅏ", "ㅏ + 아 → ㅏ", "가다 → {가요}, 자다 → {자요}"],
              ["ㅗ", "ㅗ + 아 → ㅘ", "보다 → {봐요}, 오다 → {와요}"],
              ["ㅜ", "ㅜ + 어 → ㅝ", "배우다 → {배워요}, 주다 → {줘요}"],
              ["ㅣ", "ㅣ + 어 → ㅕ", "마시다 → {마셔요}"],
              ["ㅓ, ㅕ, ㅐ", "the 어 disappears", "서다 → {서요}, 보내다 → {보내요}"],
              ["ㅡ", "ㅡ drops out", "쓰다 → {써요}, 바쁘다 → {바빠요}"],
              ["ㅚ", "ㅚ + 어 → ㅙ", "되다 → {돼요}"],
            ] } },
            { tip: "With a 받침, nothing merges: 먹 + 어요 = **먹어요**, 앉 + 아요 = **앉아요**." },
            { p: "**ㅡ stems** peek one block back: 바**쁘**다 → the block before is 바 (ㅏ) → **바빠요**. One-block stems like 쓰다 and 크다 just take 어: **써요**, **커요**." },
            { warn: "A few verbs are **irregular**: 듣다 → 들어요, 덥다 → 더워요, 모르다 → 몰라요. They get their own level later. For now, learn them as you meet them." },
            { reveal: { q: "Deep dive: 쉬다 and 되다", a: "ㅟ doesn't merge, so 쉬다 → **쉬어요** (not 쉬요). And 되다 → **돼요** (not 되요): one of the most common spelling mistakes in Korean, even among native speakers!" } },
          ],
        },
        {
          type: "steps",
          q: "Steam **보다** (*to see, to watch*).",
          start: "보다",
          steps: [
            { q: "Find the stem.", options: ["보", "봐", "보다"], answer: 0, show: "보" },
            { q: "The last vowel is ㅗ. Which ending?", options: ["아요", "어요", "해요"], answer: 0, show: "보 + 아요", hint: "ㅗ is a bright vowel." },
            { q: "No 받침, so ㅗ and ㅏ merge into…", options: ["봐요", "보요", "붜요"], answer: 0, show: "봐요" },
          ],
          explain: "ㅗ + ㅏ = ㅘ, so 보 + 아요 → **봐요**.",
        },
        {
          type: "choice",
          q: "**마시다** (*to drink*) → polite present?",
          options: ["마셔요", "마시아요", "마시요"],
          answer: 0,
          explain: "ㅣ + 어 → ㅕ: 마시 + 어요 → **마셔요**.",
          why: {
            "마시아요": "ㅣ isn't a bright vowel, so it takes 어요, and then ㅣ + 어 merge into ㅕ.",
            "마시요": "The ending's vowel can't just vanish: ㅣ + 어 merge into ㅕ → 마셔요.",
          },
        },
        {
          type: "choice",
          q: "**공부하다** (*to study*) → polite present?",
          options: ["공부해요", "공부하아요", "공부하요"],
          answer: 0,
          explain: "Every 하다 becomes **해요**: 공부해요.",
        },
        {
          type: "fix",
          sentence: "민지 씨는 지금 [가아요].",
          en: "Minji is going now.",
          options: ["가요", "거요"],
          answer: 0,
          explain: "가 + 아요: the two ㅏ merge into one → **가요**.",
        },
        {
          type: "learn",
          title: "One form, many jobs",
          blocks: [
            { p: "The 아요/어요 form is the Swiss army knife of polite Korean. **가요** can mean:" },
            { list: ["*I go, you go, she goes, they go*", "*I'm going* (right now)", "*I'm going* (soon): 내일 가요 = *I'm going tomorrow*", "*Are you going?* with a rising voice: 가요?", "*Let's go!* with the right tone: 같이 가요!"] },
            { ex: [["지금 가요.", "I'm going now."], ["지금 가요?", "Are you going now?"], ["같이 가요!", "Let's go together!"]] },
            { tip: "Context and tone do the work. Tap the speaker buttons and listen to how 가요 changes." },
          ],
        },
        {
          type: "build",
          en: "Junho is cooking.",
          tiles: ["준호 씨는", "요리해요."],
          extra: ["요리하요.", "요리어요."],
          explain: "요리하다 → 요리**해요**. The present tense also covers *is doing right now*.",
        },
        {
          type: "match",
          q: "Match each verb to its polite present form.",
          pairs: [["가다", "가요"], ["오다", "와요"], ["주다", "줘요"], ["하다", "해요"]],
        },
      ],
      notes: {
        meaning: "the polite present tense: *do / does / am doing*",
        forms: [
          ["last vowel ㅏ or ㅗ", "stem + {아요}", "살아요, 봐요"],
          ["any other vowel", "stem + {어요}", "먹어요, 마셔요"],
          ["하다 verbs", "하 → {해요}", "공부해요"],
        ],
        examples: [["저는 공부해요.", "I study. / I'm studying."], ["친구가 와요.", "My friend is coming."], ["같이 가요!", "Let's go together!"]],
        tips: [
          "Vowel stems merge: 가요, 봐요, 줘요, 마셔요, 돼요.",
          "ㅡ drops out: 써요, 바빠요.",
          "Spelling traps: **돼요** (not 되요), **쉬어요** (not 쉬요).",
          "One form = statement, question or suggestion.",
        ],
      },
    },

    /* ------------------------------------------------------------------ 2-2 */
    {
      id: "2-2",
      sticker: "을/를",
      pattern: "N을 / 를",
      title: "The object marker",
      goal: "Say what you eat, drink, watch and like: the object of the action.",
      cards: [
        {
          type: "scene",
          place: "분식집 · a snack bar",
          lines: [
            ["junho", "민지 씨, 뭐 먹어요?", "Minji, what are you eating?"],
            ["minji", "떡볶이{를} 먹어요. 준호 씨는요?", "I'm eating tteokbokki. And you?"],
            ["junho", "저는 김밥{을} 먹어요. 그리고 콜라{를} 마셔요.", "I'm eating kimbap. And I'm drinking a cola."],
            ["minji", "저도 콜라{를} 좋아해요!", "I like cola too!"],
          ],
          note: "**을 / 를** marks *what* gets eaten, drunk or liked. Can you already guess when it's 을 and when it's 를?",
        },
        {
          type: "discover",
          examples: [["떡볶이{를}", "tteokbokki"], ["김밥{을}", "kimbap"], ["콜라{를}", "cola"], ["책{을}", "book"]],
          q: "을 or 를: what's the rule?",
          options: ["을 after a consonant, 를 after a vowel", "을 for food, 를 for drinks", "을 is formal, 를 is casual"],
          answer: 0,
          explain: "You're a 받침 pro by now: 김**밥** and **책** → **을**. 떡볶**이** and 콜**라** → **를**.",
        },
        {
          type: "learn",
          title: "The object marker",
          blocks: [
            { p: "**을 / 를** marks the **object**: the thing the action happens to. *I eat* **kimbap**. *I watch* **a movie**." },
            { formula: "Noun + {을 / 를}" },
            { table: { head: ["Noun ends in", "Add", "Examples"], rows: [
              ["a consonant", "{을}", "밥{을}, 책{을}, 물{을}"],
              ["a vowel", "{를}", "커피{를}, 우유{를}, 영화{를}"],
            ] } },
            { p: "Korean word order is **topic → object → verb**. The verb always comes **last**." },
            { roles: [["저는", "I (topic)"], ["김밥을", "kimbap (object)"], ["먹어요", "eat (verb)"]] },
            { ex: [
              ["저는 커피{를} 마셔요.", "I drink coffee."],
              ["준호 씨는 책{을} 읽어요.", "Junho reads a book."],
              ["민지 씨는 영화{를} 봐요.", "Minji watches a movie."],
            ] },
            { reveal: { q: "Deep dive: can the word order change?", a: "Yes! Particles label each word's job, so you can shuffle the front: **김밥을 저는 먹어요** still means *I eat kimbap*, with a little extra focus on the kimbap. Only the verb has to stay at the end. In English, *Kimbap I eat* sounds like Yoda." } },
          ],
        },
        {
          type: "lab",
          lab: "batchim",
          pair: ["을", "를"],
          intro: "Tap a word to see whether it takes 을 or 를.",
          words: [["밥", "rice, a meal"], ["커피", "coffee"], ["책", "book"], ["영화", "movie"], ["물", "water"], ["우유", "milk"], ["음악", "music"], ["사과", "apple"], ["김치", "kimchi"], ["라면", "ramyeon"]],
        },
        {
          type: "choice",
          sentence: "저는 커피__ 마셔요.",
          en: "I drink coffee.",
          options: ["을", "를"],
          answer: 1,
          explain: "커**피** ends in a vowel → **를**.",
        },
        {
          type: "choice",
          sentence: "준호 씨는 책__ 읽어요.",
          en: "Junho reads a book.",
          options: ["을", "를"],
          answer: 0,
          explain: "**책** ends in ㄱ → **을**.",
        },
        {
          type: "build",
          en: "I watch a movie.",
          tiles: ["저는", "영화를", "봐요."],
          extra: ["영화을"],
          explain: "Topic → object → verb. 영**화** ends in a vowel → **를**.",
        },
        {
          type: "choice",
          q: "Which is the natural way to say **“I drink water.”**?",
          options: ["저는 물을 마셔요.", "저는 마셔요 물을.", "마셔요 저는 물을."],
          answer: 0,
          explain: "The verb goes **last**: 저는 물을 **마셔요**.",
        },
        {
          type: "learn",
          title: "Sneaky objects",
          blocks: [
            { p: "Some verbs take 을/를 in Korean even when English uses *with*, *to* or no object at all:" },
            { table: { head: ["Korean", "English"], rows: [
              ["친구{를} 만나요", "I meet (with) a friend"],
              ["버스{를} 타요", "I take / ride the bus"],
              ["고양이{를} 좋아해요", "I like cats"],
              ["한국어{를} 배워요", "I learn Korean"],
            ] } },
            { p: "**하다 verbs can split.** Many are *noun + 하다*, and the noun can take 을/를:" },
            { ex: [["공부해요 = 공부{를} 해요", "I study."], ["요리해요 = 요리{를} 해요", "I cook."], ["운동해요 = 운동{을} 해요", "I exercise."]] },
            { tip: "In casual speech 을/를 often drops out: **뭐 먹어요?** instead of 뭐를 먹어요? Keep it while you're learning; it's never wrong." },
            { reveal: { q: "Deep dive: 좋아요 vs 좋아해요", a: "Both can mean *I like it*, but the particles differ. **좋다** (*to be good*) is an adjective: 고양이**가** 좋아요 (*cats are good, to me*). **좋아하다** (*to like*) is an action verb: 고양이**를** 좋아해요. Same feeling, different grammar." } },
          ],
        },
        {
          type: "fix",
          sentence: "저는 [고양이을] 좋아해요.",
          en: "I like cats.",
          options: ["고양이를", "고양이 를"],
          answer: 0,
          explain: "고양**이** ends in a vowel → **를**, and particles always stick to the noun: no space.",
        },
        {
          type: "match",
          pairs: [["친구를 만나요", "I meet a friend"], ["버스를 타요", "I take the bus"], ["숙제를 해요", "I do homework"], ["음악을 들어요", "I listen to music"]],
        },
      ],
      notes: {
        meaning: "the object marker: *what* the action happens to",
        forms: [
          ["after a consonant", "N{을}", "밥을 먹어요"],
          ["after a vowel", "N{를}", "커피를 마셔요"],
          ["word order", "topic → object → {verb}", "저는 김밥을 먹어요"],
        ],
        examples: [["저는 영화를 봐요.", "I watch a movie."], ["친구를 만나요.", "I meet a friend."], ["한국어를 배워요.", "I learn Korean."]],
        tips: [
          "The verb always comes last.",
          "만나다, 타다 and 좋아하다 take 을/를.",
          "Noun + 하다 can split: 공부를 해요.",
          "Particles stick to the noun, no space.",
        ],
      },
    },

    /* ------------------------------------------------------------------ 2-3 */
    {
      id: "2-3",
      sticker: "에/에서",
      pattern: "N에 · N에서",
      title: "At, to & in (places)",
      goal: "Say where you are, where you're going, and where things happen.",
      cards: [
        {
          type: "scene",
          place: "전화 · a phone call",
          lines: [
            ["minji", "준호 씨, 지금 어디{에} 있어요?", "Junho, where are you right now?"],
            ["junho", "카페{에} 있어요.", "I'm at a café."],
            ["minji", "카페{에서} 뭐 해요?", "What are you doing at the café?"],
            ["junho", "카페{에서} 공부해요. 민지 씨는요?", "I'm studying at the café. And you?"],
            ["minji", "저는 지금 학교{에} 가요!", "I'm heading to school now!"],
          ],
          note: "**에** with 있어요 and 가요, but **에서** with 공부해요. Why? Let's find out.",
        },
        {
          type: "discover",
          examples: [["카페{에} 있어요", "I'm at a café"], ["학교{에} 가요", "I go to school"], ["카페{에서} 공부해요", "I study at a café"], ["집{에서} 쉬어요", "I rest at home"]],
          q: "When does **에서** show up?",
          options: ["When someone *does* an action at that place", "When the place is far away", "After a 받침"],
          answer: 0,
          explain: "에 goes with **being** somewhere (있어요) and **going** somewhere (가요). 에서 marks the place where you **do** something (공부해요, 쉬어요).",
        },
        {
          type: "learn",
          title: "에 vs 에서",
          blocks: [
            { table: { head: ["Particle", "Use it for", "Example"], rows: [
              ["{에}", "where something **is** (있어요 / 없어요)", "집{에} 있어요. *I'm at home.*"],
              ["{에}", "where you're **going** (가요, 와요)", "학교{에} 가요. *I go to school.*"],
              ["{에서}", "where an **action** happens", "도서관{에서} 공부해요. *I study at the library.*"],
            ] } },
            { tip: "Good news: no 받침 check! 에 and 에서 attach the same way to every noun." },
            { p: "Quick test: is the verb about **being** there or **moving toward** it? → 에. Is it about **doing something** there? → 에서." },
            { ex: [
              ["집{에} 있어요.", "I'm at home."],
              ["집{에서} 쉬어요.", "I rest at home."],
              ["회사{에} 가요.", "I go to work (the office)."],
              ["회사{에서} 일해요.", "I work at the office."],
            ] },
            { reveal: { q: "Deep dive: 에 also marks time", a: "에 is also *at / on* for time: **세 시에** (*at 3 o'clock*), **월요일에** (*on Monday*), **주말에** (*on the weekend*). But no 에 after 오늘 (*today*), 내일 (*tomorrow*) or 지금 (*now*)." } },
            { reveal: { q: "Deep dive: 에서 can also mean *from*", a: "With coming and going, 에서 can mark the starting point: **집에서 와요** (*I'm coming from home*). Context makes it clear." } },
          ],
        },
        {
          type: "sort",
          q: "에 or 에서? Ask yourself: being/going, or doing?",
          buckets: ["에", "에서"],
          items: [
            ["집__ 있어요", "I'm at home", 0, "있어요 is about **being** somewhere → **에**"],
            ["도서관__ 공부해요", "I study at the library", 1, "Studying is an **action** → **에서**"],
            ["학교__ 가요", "I go to school", 0, "가요 is about **going** somewhere → **에**"],
            ["식당__ 밥을 먹어요", "I eat at a restaurant", 1, "Eating is an **action** → **에서**"],
            ["공원__ 놀아요", "I hang out in the park", 1, "Playing / hanging out is an **action** → **에서**"],
            ["회사__ 가요", "I go to the office", 0, "가요 is about **going** → **에**"],
            ["카페__ 커피를 마셔요", "I drink coffee at a café", 1, "Drinking is an **action** → **에서**"],
            ["편의점__ 있어요", "I'm at the convenience store", 0, "있어요 is about **being** somewhere → **에**"],
          ],
          explain: "Being or going → **에**. Doing → **에서**.",
        },
        {
          type: "choice",
          sentence: "저는 지금 집__ 있어요.",
          en: "I'm at home now.",
          options: ["에", "에서"],
          answer: 0,
          explain: "있어요 is about **being** somewhere → **에**.",
        },
        {
          type: "choice",
          sentence: "카페__ 친구를 만나요.",
          en: "I meet my friend at a café.",
          options: ["에", "에서"],
          answer: 1,
          explain: "Meeting someone is an action → **에서**.",
        },
        {
          type: "build",
          en: "I study at the library.",
          tiles: ["저는", "도서관에서", "공부해요."],
          extra: ["도서관에"],
          explain: "Studying is an action → **에서**.",
        },
        {
          type: "fix",
          sentence: "저는 [공원에] 놀아요.",
          en: "I hang out in the park.",
          options: ["공원에서", "공원은"],
          answer: 0,
          explain: "놀다 (*to play, to hang out*) is an action → **에서**.",
        },
        {
          type: "choice",
          q: "How do you ask **“Where are you going?”**",
          options: ["어디에 가요?", "어디에서 가요?", "어디예요?"],
          answer: 0,
          explain: "Going → **에**. In speech, people often drop it: **어디 가요?**",
          why: {
            "어디에서 가요?": "에서 + 가요 would sound like *going from where?*",
            "어디예요?": "That's *Where is it?* or *Where are you?*",
          },
        },
        {
          type: "choice",
          q: "Trick question! **“I live in Seoul.”** Which is correct?",
          options: ["Both 서울에 살아요 and 서울에서 살아요", "Only 서울에 살아요", "Only 서울에서 살아요"],
          answer: 0,
          fixed: true,
          explain: "살다 can be seen as *being* somewhere (에) or as *doing* your living there (에서). Both are perfectly natural!",
        },
      ],
      notes: {
        meaning: "에 = at / to (being, going) · 에서 = at / in (doing)",
        forms: [
          ["being somewhere", "place{에} 있어요", "집에 있어요"],
          ["going somewhere", "place{에} 가요", "학교에 가요"],
          ["doing something", "place{에서} + action", "도서관에서 공부해요"],
        ],
        examples: [["카페에 있어요.", "I'm at a café."], ["회사에서 일해요.", "I work at the office."], ["어디 가요?", "Where are you going?"]],
        tips: [
          "No 받침 rule: same form after any noun.",
          "에 also marks time: 주말에, 세 시에.",
          "살다 works with both: 서울에 / 서울에서 살아요.",
          "에서 can also mean *from*: 집에서 와요.",
        ],
      },
    },

    /* ------------------------------------------------------------------ 2-4 */
    {
      id: "2-4",
      sticker: "안",
      pattern: "안 V · V-지 않아요",
      title: "Don't · doesn't",
      goal: "Make any verb or adjective negative, two different ways.",
      cards: [
        {
          type: "scene",
          place: "민지 씨 집 · Minji's place",
          lines: [
            ["junho", "민지 씨, 커피 마셔요?", "Minji, do you drink coffee?"],
            ["minji", "아니요, 커피는 {안} 마셔요. 차를 마셔요.", "No, I don't drink coffee. I drink tea."],
            ["junho", "나비는 우유를 마셔요?", "Does Nabi drink milk?"],
            ["minji", "아니요, 나비는 우유를 마시{지 않아요}. 물을 마셔요.", "No, Nabi doesn't drink milk. She drinks water."],
          ],
          note: "Two ways to say *don't*: **안** before the verb, or **-지 않아요** after the stem.",
        },
        {
          type: "discover",
          examples: [["{안} 마셔요", "don't drink"], ["마시{지 않아요}", "don't drink"], ["{안} 가요", "don't go"], ["가{지 않아요}", "don't go"]],
          q: "**안 마셔요** and **마시지 않아요**: what's the difference?",
          options: ["Same meaning; 안 is shorter and more casual", "안 is past tense, -지 않아요 is present", "안 is for people, -지 않아요 for animals"],
          answer: 0,
          explain: "Both mean *don't / doesn't*. **안** is short and super common in speech. **-지 않아요** is longer and sounds a little more formal; you'll see it a lot in writing.",
        },
        {
          type: "learn",
          title: "Two ways to say not",
          blocks: [
            { table: { head: ["Type", "How", "Examples"], rows: [
              ["short", "{안} + verb", "{안} 가요 · {안} 먹어요"],
              ["long", "stem + {지 않아요}", "가{지 않아요} · 먹{지 않아요}"],
            ] } },
            { p: "The long form is easy: take the stem and add **지 않아요**. No 받침 check, no vowel rules." },
            { ex: [
              ["저는 고기를 {안} 먹어요.", "I don't eat meat."],
              ["오늘은 {안} 바빠요.", "I'm not busy today."],
              ["준호 씨는 커피를 마시{지 않아요}.", "Junho doesn't drink coffee."],
            ] },
            { warn: "**Noun + 하다 verbs:** 안 goes right before 하다. 공부해요 → 공부 **안** 해요, not ~~안 공부해요~~. The long form stays simple: 공부하**지 않아요**." },
            { reveal: { q: "Deep dive: 않아요 or 안아요?", a: "Spell the long form **않아요**, with ㄶ under 아. **안아요** is a different word: *I hug*. So 먹지 않아요 = *I don't eat*, but 안아요 = *I hug*!" } },
          ],
        },
        {
          type: "steps",
          q: "Make **먹다** negative with the long form.",
          start: "먹다",
          steps: [
            { q: "Find the stem.", options: ["먹", "먹어", "먹다"], answer: 0, show: "먹" },
            { q: "Add the long negative ending.", options: ["먹지 않아요", "먹지 안아요", "먹고 않아요"], answer: 0, show: "먹지 않아요", hint: "It's always stem + 지 않아요, spelled with ㄶ." },
          ],
          explain: "Stem + **지 않아요** → 먹지 않아요. Careful: 안아요 (with ㄴ) means *I hug*!",
        },
        {
          type: "choice",
          q: "**“I don't drink coffee.”** (short form)",
          options: ["저는 커피를 안 마셔요.", "저는 안 커피를 마셔요.", "저는 커피를 마셔요 안."],
          answer: 0,
          explain: "안 goes **right before the verb**.",
        },
        {
          type: "choice",
          q: "**“I don't study.”** (공부하다, short form)",
          options: ["공부 안 해요.", "안 공부해요.", "공부해요 안."],
          answer: 0,
          explain: "With noun + 하다 verbs, 안 slips in **before 하다**: 공부 안 해요.",
        },
        {
          type: "choice",
          sentence: "오늘은 학교에 가__ 않아요.",
          en: "I'm not going to school today.",
          options: ["지", "고", "서"],
          answer: 0,
          explain: "The long negative is always **-지 않아요**.",
        },
        {
          type: "learn",
          title: "Words with their own “not”",
          blocks: [
            { p: "Some words skip 안 because they have their own opposite:" },
            { table: { head: ["Positive", "Negative", "Not this"], rows: [
              ["있어요 (*have*)", "{없어요}", "~~안 있어요~~"],
              ["알아요 (*know*)", "{몰라요}", "~~안 알아요~~"],
              ["이에요 (*is*)", "{아니에요}", "~~안 이에요~~"],
            ] } },
            { tip: "**안** = *don't / won't* (your choice). **못** = *can't* (not able). 안 가요 = *I'm not going.* 못 가요 = *I can't go.* You'll practice 못 in a later level." },
          ],
        },
        {
          type: "fix",
          sentence: "저는 돈이 [안 있어요].",
          en: "I don't have money.",
          options: ["없어요", "안 없어요"],
          answer: 0,
          explain: "있다 has its own opposite: **없어요**.",
        },
        {
          type: "build",
          en: "Junho doesn't exercise.",
          tiles: ["준호 씨는", "운동", "안", "해요."],
          extra: ["운동해요."],
          explain: "운동하다 is noun + 하다, so 안 goes before 해요: **운동 안 해요**.",
        },
        {
          type: "match",
          pairs: [["몰라요", "I don't know"], ["없어요", "I don't have it"], ["안 먹어요", "I don't eat it"], ["아니에요", "It's not"]],
        },
      ],
      notes: {
        meaning: "don't / doesn't / am not",
        forms: [
          ["short", "{안} + verb", "안 가요"],
          ["long", "stem + {지 않아요}", "가지 않아요"],
          ["noun + 하다", "noun {안} 해요", "공부 안 해요"],
        ],
        examples: [["저는 고기를 안 먹어요.", "I don't eat meat."], ["오늘은 바쁘지 않아요.", "I'm not busy today."], ["몰라요.", "I don't know."]],
        tips: [
          "안 sits right before the verb.",
          "Spell it **않아요** (안아요 means *I hug*).",
          "있어요 ↔ 없어요, 알아요 ↔ 몰라요, 이에요 ↔ 아니에요.",
          "안 = *don't*, 못 = *can't*.",
        ],
      },
    },
  ],

  quiz: {
    count: 10,
    extra: [
      {
        type: "choice",
        q: "**“I eat kimbap at home.”**",
        options: ["저는 집에서 김밥을 먹어요.", "저는 집에 김밥을 먹어요.", "저는 집에서 김밥를 먹어요.", "저는 집에서 김밥을 먹아요."],
        answer: 0,
        explain: "Doing something somewhere → **에서**. 김밥 ends in a consonant → **을**. 먹 has ㅓ → **어요**.",
      },
      {
        type: "build",
        en: "Minji doesn't watch movies.",
        tiles: ["민지 씨는", "영화를", "안", "봐요."],
        extra: ["영화을", "에서"],
        explain: "Object + 를, then **안** right before the verb.",
      },
      {
        type: "fix",
        sentence: "친구가 학교에 [오요].",
        en: "My friend comes to school.",
        options: ["와요", "워요"],
        answer: 0,
        explain: "오 + 아요 → ㅗ + ㅏ merge into ㅘ → **와요**.",
      },
      {
        type: "choice",
        q: "**쉬다** (*to rest*) → polite present?",
        options: ["쉬어요", "쉬요", "숴요"],
        answer: 0,
        explain: "ㅟ doesn't merge with 어: **쉬어요**.",
      },
      {
        type: "choice",
        sentence: "저는 도서관__ 책을 읽어요.",
        en: "I read books at the library.",
        options: ["에", "에서"],
        answer: 1,
        explain: "Reading is an action → **에서**.",
      },
    ],
  },
});
